Lab 1
edr3x/cloud-computing-assignments pull request #1
Opened 2023-06-23 13:09 UTC by edr3x

Lab 1 complete

2023-06-27 12:16 UTC, ritushishir requested changes

2023-06-27 12:16 UTC, ritushishir commented on app-script-payslip-sender/email_sender.gs
> +    let [Name, Email, Salary] = values[i];
better to follow the standard naming convention for variables in JavaScript.

https://www.30secondsofcode.org/js/s/naming-conventions/

2023-06-27 12:16 UTC, ritushishir commented on app-script-payslip-sender/email_sender.gs
> +        console.log(err);
does it execute without an error?

2023-06-27 12:17 UTC, ritushishir commented on app-script-email-for-form-submission/thank_you_email.gs
> +  if (isValidEmail(email)) {
👍

2023-07-01 06:35 UTC, edr3x commented
all requested changes applied!

2023-07-02 00:49 UTC, ritushishir commented on app-script-payslip-sender/email_sender.gs
> +        console.log(err);
This line raises another error in App Script. Can you try with few inputs that triggers this line?

2023-07-02 00:49 UTC, ritushishir approved these changes

2023-07-08 14:30 UTC, merged